### ISSUE TITLE
os.environ['HOME'] not supported on Windows

### ISSUE THREAD

**Issue by tonywagner** [kmac/mlbv#17]
The reference "os.environ['HOME']" in config.py, line 56, causes the program to fail with "KeyError: 'HOME'" when running on Windows.

Changing that reference to:
`os.path.expanduser('~')`

fixes it, and still works fine on my non-Windows systems (Mac OS X and Android).

**Comment by kmac** [comment]
Thanks I will make that change over the next week.

**Comment by kmac** [comment]
Fixed in v0.0.6
