### ISSUE TITLE
Add support for streamlink's "--player-external-http" options

### ISSUE THREAD

**Issue by tonywagner** [kmac/mlbv#22]
It might be nice to add support for Streamlink's --player-external-http and --player-external-http-port options, so we could direct the stream to a port rather than to a video player or a file. Makes it easier to run mlbv on one device, while watching on a different one which may not support mlbv (like an Apple TV).

[https://streamlink.github.io/cli.html#cmdoption-player-external-http](url)

Not sure how you'd want to implement this. Easiest might be a "--port" option, which could be followed by an optional port number, that one could use instead of "--fetch"? Or if you don't want to do that, simply adding a "streamlink_args" option to the config file like mlbstreamer could work too.

**Comment by kmac** [comment]
Good suggestion... I'll look at adding the streamlink_args, that seems to be a more general way of approaching it. I suspect it may require different streamlink args for live/archived games vs. recaps/condensed.

**Comment by tonywagner** [comment]
I don't use mlbv for anything but live games, so I think it could still be useful just in that context.

Here's what I did to make it happen:

1. In mlbv.py, I added a "port" argument, which can either be supplied by the user ("--port 10000"), set to zero by just "--port" (which lets Streamlink choose a random high port > 1024), or defaults to -1 (in which case we can ignore it):
```python
    parser.add_argument("--port", type=int, nargs='?', const=0, default=-1,
                        help="Stream to local HTTP port instead of playing or saving to file (live or full games only)")
```

Then I added that new port argument to end of the full game (non-recap) call for play_stream():
```python
    return stream.play_stream(game_rec, team_to_play, feedtype, args.date, args.fetch, args.from_start, args.inning, args.port)
```

2. Then in stream.py, I added the new port argument to the definitions/calls of play_stream() and streamlink():
```python
def play_stream(game_rec, team_to_play, feedtype, date_str, fetch, from_start, inning_ident, is_multi_highlight=False, port=-1):
```
```python
                streamlink(stream_url, mlb_session, get_fetch_filename(date_str, game_rec, feedtype, fetch), from_start, offset, port)
```
```python
def streamlink(stream_url, mlb_session, fetch_filename=None, from_start=False, offset=None, port=-1):
```

And finally, I added another IF condition before the "if fetch_filename" one in streamlink(), as follows:
```python
    if port != -1:
        streamlink_cmd.append("--player-external-http")
        streamlink_cmd.append("--player-external-http-port")
        streamlink_cmd.append(str(port))
        LOG.info("Streaming to local HTTP port, see output below for playback URL")
    elif fetch_filename is not None:
```

**Comment by kmac** [comment]
Here's what I am testing.

- add streamlink_custom_args config property

Then you would setup streamlink_custom_args to include the player-external-http options, like this:

````
# Custom streamlink arguments. 
# If set, these arguments are appended to the streamlink arguments before sent to the player.
# This is a comma-separated list of variables. Each argument should be separated by a comma.
# For example to use streamlink's external http player, you can set the video_player to an empty
# string, and then use the following streamlink_custom_args to have streamlink publish on port 8080:
streamlink_custom_args=--player-external-http,--player-external-http-port,8080
````
And then you unset the video_player:
````
video_player=
````
And it will invoke streamlink with the additional arguments given. In this case the runtime output looks like this:

````
[cli][info] Available streams: 180p (worst), 216p, 288p, 360p, 504p, 540p, 720p_alt, 720p (best)                                                                                
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:8080/
````

With some changes to stream.py this should work for all video options - recaps, live, archived, etc.

**Comment by kmac** [comment]
In release v0.0.8
