### ISSUE TITLE
Unable to view archived games from past years.

### ISSUE THREAD

**Issue by jstack01** [kmac/mlbv#26]
It seems that i cant pull up any archived games from other years. The console always shows this error: "KeyError: 'mediaPlaybackId'" Games from 2018 work fine.

Console output (2018 game)
mlbv -d 2018-08-13 -t nyy

Default (home/away) feed not found: choosing first available feed
Chose 'national' feed (override with --feed option)
[cli][info] Found matching plugin hls for URL https://hlslive-akc-ewr1.media.mlb.com/hdnts=exp=1543377560~acl=/*~id=24982353~data=eb223734-de75-40af-ba55-3c3864523da3~hmac=a8436d36ce28d6c6457ea552fc8847816ea0e6e5e962de1297bc343dad72fee6/a7522342d8fec8a44d530ca31ba2a57b/ls01/mlb/2018/08/13/National_VIDEO_eng_New_York_Mets_New_York_Ya_20180813_1534193389378/master_desktop_complete-trimmed.m3u8
[cli][info] Available streams: 180p (worst), 216p, 288p, 360p, 504p, 540p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls-multi)
[cli][info] Starting player: /usr/bin/vlc

Console output (2017 game)
mlbv -d 2017-08-13 -t nyy

Default (home/away) feed not found: choosing first available feed
Chose 'national' feed (override with --feed option)
Traceback (most recent call last):
  File "/home/jstack01/.local/bin/mlbv", line 11, in <module>
    sys.exit(main())
  File "/home/jstack01/.local/lib/python3.6/site-packages/mlbam/mlbv.py", line 261, in main
    return stream.play_stream(game_rec, team_to_play, feedtype, args.date, args.fetch, args.from_start, args.inning)
  File "/home/jstack01/.local/lib/python3.6/site-packages/mlbam/stream.py", line 101, in play_stream
    media_playback_id, media_state = select_feed_for_team(game_rec, team_to_play, feedtype)
  File "/home/jstack01/.local/lib/python3.6/site-packages/mlbam/stream.py", line 43, in select_feed_for_team
    return game_rec['feed'][feedtype]['mediaPlaybackId'], game_rec['feed'][feedtype]['mediaState']
KeyError: 'mediaPlaybackId'

**Comment by tonywagner** [comment]
MLB changed the system in 2018, so what works for 2018 games no longer works for old games.

Here is an alternate method to find old games via YouTube:
https://www.reddit.com/r/baseball/comments/51ghh1/psa_how_to_watch_any_mlb_game_since_2009_for_free/

I was also able to install the 2017 version of the unofficial Kodi addon via zip file to access 2017 games too:
https://github.com/eracknaphobia/plugin.video.mlbtv/archive/3c36ee8df475b28e775a09678d24dbe1b76b00f0.zip

**Comment by jstack01** [comment]
Cool how would I install the kodi add on on Linux?

**Comment by tonywagner** [comment]
Did the YouTube method not work? That would be relatively easy to download, using youtube-dl

Not an easy way to download with Kodi, but it is possible. Download ffmpeg, and then edit Kodi's playercorefactory file to use it? You'd have to pass both the video url and cookie authorization header for MLB, maybe it would be easier to edit the addon code.

https://github.com/NapoleonWils0n/kodi-playercorefactory

**Comment by kmac** [comment]
Sorry @jstack01 I haven't had any time this week to look at this at all (any time I have on this is currently spent trying to bring nhlv up to the more recent changes I've made in mlbv, and I'm trying to refactor them to use the same code base).
 
I'm not sure if there would be a lot of work here to get things working with older games. I'll see if I can find some time to poke around at it over the next week.

**Comment by jstack01** [comment]
@kmac thanks!

**Comment by kmac** [comment]
Not planning to support this, unless someone else wants to take a crack at it.
