### ISSUE TITLE
Not downloading alternate audio tracks

### ISSUE THREAD

**Issue by mlb-fan** [kmac/mlbv#27]
Is this feature referenced here still working? https://github.com/kmac/mlbv/issues/14

I just installed the program and downloaded my first game. The video and tv audio work great, but there is no radio feed on the file. There are no alternate audio tracks at all actually, I only have one (English tv) even though in the config file it is set to * to download all audio tracks.

The primary use I want this program for is specifically to access the radio broadcasts for games, so please help me determine why I didn't get it.

**Comment by tonywagner** [comment]
Check if your Streamlink is at least version 0.12.0, and that your ffmpeg is at least 4.0.

**Comment by kmac** [comment]
I'm away and not around a cheap internet connection right now, but this was definitely working for live games. I'm not sure for archived games. It's definitely dependent on the newish feature provided by the version of streamlink/ffmpeg listed above though.

**Comment by mlb-fan** [comment]
Sorry, how do I check the version?

**Comment by kmac** [comment]
Use `streamlink --version` and `ffmpeg -version`. Note one uses two dashes and the other uses a single.

**Comment by mlb-fan** [comment]
streamlink is 0.14.2
'ffmpeg' is not recognized as an internal or external command,

It must be installed because the download works, but never got added to Path? How can I find its location?

**Comment by tonywagner** [comment]
It comes with Streamlink. Find the folder where Streamlink is installed, then it should be under Dependecies/ffmpeg. You can drag the ffmpeg.exe file onto the command prompt and hit enter to run it and see what version it returns.

If it is less than 4.0, download a new version here, and replace the old ffmpeg.exe:
https://ffmpeg.zeranoe.com/builds/

**Comment by mlb-fan** [comment]
I can't find where streamlink got installed to? Sorry I'm not good with command line stuff. I just ran whatever install command I found online and it worked. I didn't specify a directory. I'm on Windows if that makes a difference.

**Comment by tonywagner** [comment]
On the Windows command prompt, just type "where streamlink" and it should return the folder. If you just used the Windows installer for Streamlink, it could be in "C:\Program Files\Streamlink\bin", and its bundled ffmpeg would be at "C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe"

I seem to recall Streamlink was bundled with ffmpeg 3.x and I had to download ffmpeg 4 to replace it before the alternate audio tracks worked.

**Comment by mlb-fan** [comment]
Hmm, that worked to find the location, but it doesn't fit with the description in your previous message.
"where streamlink" returned AppData\Local\Programs\Python\Python37-32\Scripts\streamlink.exe
I went there, and that's where the streamlink file is, but there is no Dependencies folder.

**Comment by tonywagner** [comment]
Yeah, sorry, there are a bunch of different ways to install.

Is there a ffmpeg.exe in that folder? If not, download one from the following link, drop it in there, and see what happens.

https://ffmpeg.zeranoe.com/builds/

**Comment by tonywagner** [comment]
You could uninstall Streamlink via pip, and then just install it with its own Windows .exe installer from here:

https://github.com/streamlink/streamlink/releases/tag/0.14.2

Then ffmpeg should be at "C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe" or thereabouts as mentioned earlier.

**Comment by mlb-fan** [comment]
I downloaded the newest build again, unzipped it and copied the ffmpeg.exe that was in the bin directory into this directory, and now the command prompt says:
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017

Is this what I should try? Do I need anything else from the zip, there were other files in it.

**Comment by tonywagner** [comment]
Nope, that should be it. Do you see the audio tracks now, in mlbv?

**Comment by mlb-fan** [comment]
Oh, now when I use the same download command I have been trying the whole time it does this:

Traceback (most recent call last):
  File "C:\...\AppData\Local\Programs\Python\Python37-32\Scripts\mlbv-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\...\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 3126, in <module>
    @_call_aside
  File "c:\...\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "c:\...\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\...\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "c:\...\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\...\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'streamlink' distribution was not found and is required by mlbv

**Comment by mlb-fan** [comment]
I assume this is because I removed the pip version of it and that's the the program is looking for? How do I make it use the one I just installed via the executable?

**Comment by mlb-fan** [comment]
I assume this is because I removed the pip version of Streamlink and that's what the program is looking for? How do I make it use the one I just installed via that executable?

**Comment by tonywagner** [comment]
Okay, I think I found an easier solution. In your mlbv config file, just specify the path of your ffmpeg.exe to send to Streamlink, as follows:

streamlink_extra_args=--ffmpeg-ffmpeg,"c:\path\to\ffmpeg.exe"

You could reinstall Streamlink by pip too, if necessary to get that part working again. You could even uninstall the other Streamlink, as long as you leave the ffmpeg.exe somewhere, anywhere, and specify that path as described above.

**Comment by mlb-fan** [comment]
Ah I see! No I hadn't done that.

Now I used "pip install streamlink" and the config file had the path to the ffmpeg.exe I downloaded.
mlbv runs again now, but still only has the one audio track...

**Comment by mlb-fan** [comment]
Please help me figure this out, my MLB.tv account expires soon I need to get a few certain games downloaded.

**Comment by kmac** [comment]
Sorry, I can't be of any help. I don't have any Windows installations (nor do I want to, for reasons like this!). 
Anyway there's really nothing in this package that is specific to this issue at all. We're just relying on a feature of streamlink to provide the alternate audio feeds, which are part of the data that comes back from the mlb site. If you can get your streamlink properly updated to the newest version it should work.

**Comment by mlb-fan** [comment]
Can you at least determine if this even works in the first place? You said you didn't know about archived games, maybe I don't have a problem with the setup after all and it just doesn't get alternate audio in any case.

This is the command I've been testing with:`mlbv --date 2018-06-24 -t sf --fetch`

**Comment by kmac** [comment]
Uhhh, damn. I just tried that and yes I'm only seeing one audio source on any of the archived games that I've tried. Sorry about this confusion. When you originally asked for help over the holidays I wasn't anywhere near the internet, and @tonywagner was doing such a great job I hadn't checked the archived games.

However, I'm really not sure what's going on. Running your command above with the --debug option, `mlbv --debug --date 2018-06-24 -t sf` dumps the playlist file into the system temp directory (on my linux box the extra debug info goes into /tmp/mlbv; on windows it's somewhere in your profile directory under 'Temp' I think...). 

In there, the playlist file (playlist-2019-01-22.m3u8) looks like this:

````
#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="English",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="cc",LANGUAGE="en",NAME="English",INSTREAM-ID="CC1"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="Natural Sound",LANGUAGE="zxx",AUTOSELECT=NO,URI="ballpark_48K/48_complete-trimmed.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="English Radio",LANGUAGE="en",AUTOSELECT=NO,URI="eng_48K/48_complete-trimmed.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="Radio EspaÃ±ola",LANGUAGE="es",AUTOSELECT=NO,URI="spa_48K/48_complete-trimmed.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=2120000,RESOLUTION=896x504,FRAME-RATE=29.97,CODECS="mp4a.40.2,avc1.4d001f",CLOSED-CAPTIONS="cc",AUDIO="aac"
1800K/1800_complete-trimmed.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=153000,RESOLUTION=320x180,FRAME-RATE=29.97,CODECS="mp4a.40.2,avc1.4d001f",CLOSED-CAPTIONS="cc",AUDIO="aac"
192K/192_complete-trimmed.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=620000,RESOLUTION=400x224,FRAME-RATE=29.97,CODECS="mp4a.40.2,avc1.4d001f",CLOSED-CAPTIONS="cc",AUDIO="aac"
514K/514_complete-trimmed.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=960000,RESOLUTION=512x288,FRAME-RATE=29.97,CODECS="mp4a.40.2,avc1.4d001f",CLOSED-CAPTIONS="cc",AUDIO="aac"
800K/800_complete-trimmed.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1400000,RESOLUTION=640x360,FRAME-RATE=29.97,CODECS="mp4a.40.2,avc1.4d001f",CLOSED-CAPTIONS="cc",AUDIO="aac"
1200K/1200_complete-trimmed.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2950000,RESOLUTION=960x540,FRAME-RATE=29.97,CODECS="mp4a.40.2,avc1.4d001f",CLOSED-CAPTIONS="cc",AUDIO="aac"
2500K/2500_complete-trimmed.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4160000,RESOLUTION=1280x720,FRAME-RATE=29.97,CODECS="mp4a.40.2,avc1.640028",CLOSED-CAPTIONS="cc",AUDIO="aac"
3500K/3500_complete-trimmed.m3u8
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=62000,RESOLUTION=400x224,CODECS="avc1.4d001f,mp4a.40.2",URI="514K/514_complete_iframe-trimmed.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=295000,RESOLUTION=960x540,CODECS="avc1.4d001f,mp4a.40.2",URI="2500K/2500_complete_iframe-trimmed.m3u8"
````

Now, that looks to me like it has the alternate audio streams in it (the fields with EXT-X-MEDIA:TYPE=AUDIO), but my player isn't recognizing them for some reason. I'm not sure if this something that is now broken on my system or not.

Hey @tonywagner, would you mind running @mlb-fan's command there, and seeing if you get the alternate audio feeds? Much appreciated!

**Comment by mlb-fan** [comment]
To clarify, you're thinking the other audio *is* actually in the downloaded file and the media player just doesn't see it? Or that the alternate audio is present in the download target but isn't being included in the file that the fetch creates for some reason.

**Comment by tonywagner** [comment]
I just tried it on my Windows system, where I have an old, modified mlbv configured to stream to a port, and opening the stream in VLC shows all 4 audio tracks for that game, and all are working. So MLB is still serving them.

I'll see if I can reproduce this on a stock mlbv install tomorrow.

**Comment by kmac** [comment]
Okay, that makes sense with what I see in the .m3u8 file: the alternate tracks are there. Thanks @tonywagner 

For some reason in my setup I'm not getting them in my player, but I'm running out of a dev branch and I probably broke something. 

So @mlb-fan: yes, it should work for you if you get the proper streamlink setup. Ignore what I was saying about it not working for me.

**Comment by tonywagner** [comment]
Just tried it on a fresh Windows VM, with mlbv 0.0.5 and Streamlink 0.14.2. All audio streams downloaded fine.

If kmac doesn't mind, here is a link to the mlbv Windows installer I made last summer and the instructions I used. No Python necessary.

https://www.reddit.com/r/MLBtv/comments/8vo6ny/the_new_2018_mlbtv_web_player_is_so_bad/e27v12u/

**Comment by mlb-fan** [comment]
Thank you! I will try that - do I need to get rid of everything I've tried to do so far and start over? Or will running that work over whatever is already in place to fix anything that's wrong?

**Comment by tonywagner** [comment]
If you don't have any other need for Python, you may as well uninstall it and delete the folder.

**Comment by mlb-fan** [comment]
It's working!! Thank you SO much!!

**Comment by tonywagner** [comment]
Glad to hear it!
