### ISSUE TITLE
Issue playing recaps

### ISSUE THREAD

**Issue by mvs2** [kmac/mlbv#32]
Hello,

First, thank you so much for what you've done.  If I'm turning this in incorrectly, please forgive and I'll move on.  This work is highly appreciated and I have nothing but gratitude for the project.

My issue is currently recaps don't seem to work for me.  I get an error.  Example:

> mlbv --yesterday --recaps nyy
> Playing recap for DET at NYY
> No playback_url found for det vs nyy
> FATAL: No playback url for feed 'recap'

I'm wondering if somehow the URL for the recaps is different this season?

**Comment by kmac** [comment]
Yes they seem to have moved the feeds around.

Incidentally, I'm now seeing issue #31 in my world, which is an authentication issue with mlb.tv - they've changed it around. I'm likely going to abandon this effort and suggest people move to using the new [streamglob](https://github.com/tonycpsu/streamglob) project, which does, or will do, all of both mlbv and nhlv.

**Comment by kmac** [comment]
Fixed
