### ISSUE TITLE
Issue when trying to play any game: "IndexError: list index out of range"

### ISSUE THREAD

**Issue by VirtualParticle** [kmac/mlbv#33]
When attempting to play any game, I recieve the following error message.

```
mlbv -t nyy

Traceback (most recent call last):
  File "C:\Python37\Scripts\mlbv-script.py", line 11, in <module>
    load_entry_point('mlbv==0.0.8', 'console_scripts', 'mlbv')()
  File "c:\python37\lib\site-packages\mlbam\mlbv.py", line 261, in main
    return stream.play_stream(game_rec, team_to_play, feedtype, args.date, args.fetch, args.from_start, args.inning)
  File "c:\python37\lib\site-packages\mlbam\stream.py", line 99, in play_stream
    mlb_session = session.MLBSession()
  File "c:\python37\lib\site-packages\mlbam\session.py", line 81, in __init__
    self.login()
  File "c:\python37\lib\site-packages\mlbam\session.py", line 104, in login
    if self.is_logged_in():
  File "c:\python37\lib\site-packages\mlbam\session.py", line 139, in is_logged_in
    if "Login/Register" in data.xpath(".//title")[0].text:
IndexError: list index out of range
```

The issue occurs even on a fresh installation with no sign-in information supplied. I tried it on two computers, both Windows 10 machines with Python 3.7. They were both working fine just yesterday, so I assume the problem is something on MLB.tv's side, but I'm not sure.

**Comment by kmac** [comment]
I have been meaning to update this project to state that MLB broke the login back at the start of the season. 
There is another project over at https://github.com/tonycpsu/streamglob which is being actively developed and I've switched over to for watching games. I still use mlbv for checking scores and schedules though, so I will probably keep it alive for everything except watching games. Or, I may just have it launch streamglob for that part of it.

**Comment by VirtualParticle** [comment]
Okay I'll try to get that working. The project almost seems like it is intentionally trying to not work on Windows; there's a Python library it uses called "blist" which is some apparently more efficient list data type which is near impossible to get working on Windows. I swear if I can't get that working I'll just try to fork it and make it work myself.

**Comment by VirtualParticle** [comment]
Update: I couldn't get streamglob working since it inherently is incompatible with Windows due to the way its terminal interface works. I did manage to modify MLBv by taking a bunch of code from there, and it works!

[Here's the PR](https://github.com/kmac/mlbv/pull/34)

**Comment by kmac** [comment]
Closing this off now since this is back up and working. Thanks.
