### ISSUE TITLE
Error handling / retry function for failed downloads

### ISSUE THREAD

**Issue by wisem2540** [kmac/mlbv#42]
Currently I am forced to manually verify file size.  I assume anything below 7GB is a failed DL.  This is not always reliable.  It would be nice if mlbv could catch its own errors

**Comment by SlimJimPoisson** [comment]
I would second this idea. Some way to resume based on specific time (not inning). I don't know if that's possible, but any glitchy connection leads to complete frustration. Clearly, no bug in Kmac's work, but very useful all the same.

**Comment by kmac** [comment]
It looks like I should be passing check=True into the subprocess.run call. I will experiment with this. I'm not sure that mlbv will actually do anything with this info, but at least it could exit with a non-zero exit code which you can then test for and take appropriate action.

**Comment by kmac** [comment]
Fixed in latest git. Release will be upcoming.
