### ISSUE TITLE
Can't connect to a game

### ISSUE THREAD

**Issue by Yankees4life** [kmac/mlbv#45]
Hello

I'm trying to watch an archived game but the connection just hangs and times out eventually

> C:\Users\Jean\AppData\Local\Programs\Python\Python38-32\Scripts>mlbv --yesterday
>  -t laa
> [cli][info] Found matching plugin hls for URL https://hlslive-akc-ewr1.media.mlb
> .com/hdnts=exp=1596519753~acl=/*~id=00u7pzlf65UCoAWdq356~data=5190ffd6-75ab-41ac
> -ab2a-e0bfaf6664f2~hmac=08d21d931e2b2eaabc347ff3490b5ed0b3c8cb60bc9ff63e6a78e41b
> cda9b0b9/fdca4d6842ce6a6f967f17dde9a2fc25/ls01/mlb/2020/08/02/Home_VIDEO_spa_Hou
> ston_Astros_Los_Angele_20200802_1596393611093/master_desktop_complete-trimmed.m3
> u8
> [cli][info] Available streams: 180p (worst), 216p, 288p, 360p, 504p, 540p, 720p_
> alt, 720p (best)
> [cli][info] Opening stream: 540p (hls-multi)
> [stream.hls][error] Failed to create decryptor: Unable to open URL: https://play
> back.svcs.mlb.com/silk/events/daecb582-a7ff-4cc1-b320-50d240186f5c/media/5190ffd
> 6-75ab-41ac-ab2a-e0bfaf6664f2/keys/31f90f0f-7742-4cdd-8429-04b7dcbf09b1 (HTTPSCo
> nnectionPool(host='playback.svcs.mlb.com', port=443): Max retries exceeded with
> url: /silk/events/daecb582-a7ff-4cc1-b320-50d240186f5c/media/5190ffd6-75ab-41ac-
> ab2a-e0bfaf6664f2/keys/31f90f0f-7742-4cdd-8429-04b7dcbf09b1 (Caused by NewConnec
> tionError('<urllib3.connection.HTTPSConnection object at 0x062E27D8>: Failed to
> establish a new connection: [WinError 10060] A connection attempt failed because
>  the connected party did not properly respond after a period of time, or establi
> shed connection failed because connected host has failed to respond')))
> [stream.hls][error] Failed to create decryptor: Unable to open URL: https://play
> back.svcs.mlb.com/silk/events/daecb582-a7ff-4cc1-b320-50d240186f5c/media/5190ffd
> 6-75ab-41ac-ab2a-e0bfaf6664f2/keys/31f90f0f-7742-4cdd-8429-04b7dcbf09b1 (HTTPSCo
> nnectionPool(host='playback.svcs.mlb.com', port=443): Max retries exceeded with
> url: /silk/events/daecb582-a7ff-4cc1-b320-50d240186f5c/media/5190ffd6-75ab-41ac-
> ab2a-e0bfaf6664f2/keys/31f90f0f-7742-4cdd-8429-04b7dcbf09b1 (Caused by NewConnec
> tionError('<urllib3.connection.HTTPSConnection object at 0x062E27F0>: Failed to
> establish a new connection: [WinError 10060] A connection attempt failed because
>  the connected party did not properly respond after a period of time, or establi
> shed connection failed because connected host has failed to respond')))
> [cli][error] Try 1/1: Could not open stream <Stream()> (No data returned from st
> ream)
> error: Could not open stream <Stream()>, tried 1 times, exiting
> [cli][info] Closing currently open stream...

**Comment by kmac** [comment]
I'm going to close this for now. I assume this was some issue with the backend service. You can re-open if it's still an issue.
