### ISSUE TITLE
Can't view archive games for August 28, 2020 only

### ISSUE THREAD

**Issue by nchaturv1994** [kmac/mlbv#46]
When I try to watch footage from any game from August 28, 2020, I get the following error. It works for any other game on any other day from this season, which makes the error that much more confusing.

`Traceback (most recent call last):
  File "/opt/anaconda3/bin/mlbv", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/mlbv/mlbam/mlbv.py", line 237, in main
    game_day_tuple_list = gamedata_retriever.process_game_data(args.date, args.days)
  File "/opt/anaconda3/lib/python3.7/site-packages/mlbv/mlbam/mlbgamedata.py", line 270, in process_game_data
    game_records = self._get_games_by_date(game_date)
  File "/opt/anaconda3/lib/python3.7/site-packages/mlbv/mlbam/mlbgamedata.py", line 249, in _get_games_by_date
    game_rec['feed'][feedtype]['mediaPlaybackId'] = str(stream['mediaPlaybackId'])
KeyError: 'mediaPlaybackId'`

This error occurs regardless of whether I specify a game with: 

`mlbv --team mia --date 2020-08-28`

Or if I just try looking at the schedule for that day:

`mlbv --date 2020-08-28 `

Is anyone else able to reproduce this issue, or does anyone know if I'm doing anything wrong?

**Comment by kmac** [comment]
Indeed, this looks like something unexpected in the feed data for this day. Needs to be handled.

**Comment by kmac** [comment]
Fixed in latest git. Release will be upcoming.
