### ISSUE TITLE
Getting a 403 Client Error

### ISSUE THREAD

**Issue by 68michael** [kmac/mlbv#47]
First day of Spring Training baseball! Just wanted to pass along that I'm getting a 403 Client Error -- login ID and password are up to date and correct. Here's the message from the command line when I just type "mlbv":
"requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://statsapi.mlb.com/api/v1/schedule?sportId=1&startDate=2021-02-28&endDate=2021-02-28&hydrate=broadcasts(all),game(content(all)),linescore,team"
I'm getting the same 403 error no matter what date I put in.
(edit: Never mind, I solved it. My VPN was blocking things.)

**Comment by GTRcktSci** [comment]
@68michael can you confirm how you fixed this?  I'm having the same issue with my VPN (using nordvpn), but not sure what/where to unblock.

**Comment by 68michael** [comment]
I finally gave up and disconnected my VPN and the download proceeded
smoothly. I wish there were another way to fix it, but I wasn't able to
find one. I know MLB.TV has an issue with VPNs trying to get around
blackouts; maybe that's what's causing it.

**Comment by GTRcktSci** [comment]
Thanks for the reply.  I finally got mine working with the VPN, but then I
upgraded my Raspberry Pi 2 to a 3 to get the wifi and now the feeds stops
after about 30 seconds, so now I need to troubleshoot that.
