### ISSUE TITLE
Feature Request: convenience method for "days ago"

### ISSUE THREAD

**Issue by trevorcortez** [kmac/mlbv#49]
You should be able to say:

`mlbv --days -- -3`

…which would show you the past 3 days.  

Something like:
```
    if args.days < 0:
        args.date = datetime.strftime(datetime.today() - timedelta(abs(days)), "%Y-%m-%d")
```

Could also be achieved with other flags like ``--days 3 --ago``

**Comment by kmac** [comment]
This is a most excellent idea. I'll look at it when I get some time over the next couple of weeks.

**Comment by kmac** [comment]
FYI, I just remembered that you sort of do this already, just start it from a given date in the past: mlbv --date 2021-04-01 --days 3

It's not as easy to use though, and as your snippet suggests, it should be easy enough to do.

**Comment by kmac** [comment]
Fixed in latest git. Release will be upcoming.
