### ISSUE TITLE
Current standings are off by a day

### ISSUE THREAD

**Issue by kmac** [kmac/mlbv#5]
For some reason the stats api is returning yesterday's standings when given today's date. 

I'm going to leave things as-is for now hoping that it's an issue on the mlb stats api side that gets resolved. For now if you want to see the current standings use '--standings --tomorrow'

**Comment by snipem** [comment]
Maybe it’s related to different timezones? We had such a problem over at mlbstreamer

**Comment by kmac** [comment]
It's possible I suppose... although I checked the URL I'm sending in - it has today's date (2018-04-03) in it:

    https://statsapi.mlb.com/api/v1/standings/byDivision?leagueId=103,104&season=2018&date=2018-04-03&hydrate=division,conference,sport,league,team

The 'lastUpdated' fields returned in the response are all: "2018-04-02T13:48:39.000Z"

Then changing the URL to tomorrow:

    https://statsapi.mlb.com/api/v1/standings/byDivision?leagueId=103,104&season=2018&date=2018-04-04&hydrate=division,conference,sport,league,team

And the 'lastUpdated' field becomes: "2018-04-03T13:14:04.000Z"

Which really seems like a bug in the API. Or it's quite possible that I'm using it wrong. It seemed work properly a few days ago.

**Comment by kmac** [comment]
Fixed. Removing the date= field for the current date resolved it.
