### ISSUE TITLE
Could not load stream - blackout

### ISSUE THREAD

**Issue by mkomko** [kmac/mlbv#51]
When I try to play a game from today (live or archived), I get the following blackout error:
```
$ mlbv --team pit
Could not load stream
{'errors': ['blackout']}
No stream URL found
```
Of course I am not really blacked out as I'm in Europe and I can play the games in the browser.
Games from yesterday or the day before work fine.

Running mlbv with --debug and --verbose yields no additional helpful information.

I would appreciate any help debugging! Does anyone else have the same problem?
Thank you very much in advance.

**Comment by kmac** [comment]
If you look at https://www.reddit.com/r/MLBtv there are lots of people complaining about being blacked out on various devices. I had trouble on my firestick yesterday (April 3), whereas I could watch via mlbv. So hopefully these are just some hiccups that go away in the next day or two.

**Comment by mkomko** [comment]
Thanks for the information, I'll keep an eye on it in the coming days.

**Comment by mkomko** [comment]
Same thing today.

**Comment by garytee** [comment]
If you're still having an issue, try deleting the session and cookies file in ~/.config/mlbv

**Comment by mkomko** [comment]
@garytee Thanks for the tip, but the problem persists :-(

```
$ rm ~/.config/mlbv/session && rm ~/.config/mlbv/cookies

$ mlbv

       2021-04-06 Tue                            Series  │   State   │ Feeds
─────────────────────────────────────────────────────────┼───────────┼────────────────
19:10: Minnesota (MIN) at Detroit (DET)            2/3   │   Live    │ a,h
22:05: Atlanta (ATL) at Washington (WSH)           2/3   │ Pre-Game  │
22:07: Houston (HOU) at LA Angels (LAA)            2/2   │ Pre-Game  │
00:35: Baltimore (BAL) at NY Yankees (NYY)         2/3   │           │
00:40: Pittsburgh (PIT) at Cincinnati (CIN)        2/3   │ Pre-Game  │
00:40: St. Louis (STL) at Miami (MIA)              2/3   │           │
01:05: NY Mets (NYM) at Philadelphia (PHI)         2/3   │           │
01:10: Tampa Bay (TB) at Boston (BOS)              2/3   │           │
01:40: Milwaukee (MIL) at Chi Cubs (CHC)           2/3   │           │
02:05: Toronto (TOR) at Texas (TEX)                2/3   │           │
02:40: Arizona (ARI) at Colorado (COL)             1/3   │           │
03:40: LA Dodgers (LAD) at Oakland (OAK)           2/3   │           │
04:10: San Francisco (SF) at San Diego (SD)        2/3   │           │
04:10: Chi White Sox (CWS) at Seattle (SEA)        2/3   │           │

$ mlbv --team det
Could not load stream
{'errors': ['blackout']}
No stream URL found
```

**Comment by garytee** [comment]
Weird, I've had some issues with false flag blackouts but I'm pretty surprised it's happening to you in Europe. have you modified anything in your network settings or have a VPN running?  I would remove the cookies & session files again, create a new network location with default dns and give it another try.

**Comment by mkomko** [comment]
@garytee You are a genius, how did you come up with that? Thank you so much!
My Linux PC is permanently connected to a VPN, also in Europe. Once disconnected I was able to watch live games again after deleting the cookies and session files.

I guess MLBAM must be monitoring known VPNs and blacking them out. Good to know, I never would have guessed.

Issue closed!
