### ISSUE TITLE
Inning start times are incorrect for archived games

### ISSUE THREAD

**Issue by kmac** [kmac/mlbv#7]
After a game is archived (non-live), the inning start times seem to be off.

Seeing this now on the Boston game. I must be calculating the offset incorrectly. Probably because I'm using the scheduled start time and not the actual start time.

**Comment by kmac** [comment]
I must be missing a data point which would give me the start timestamp of the video, or even the final timestamp of where the video ends. I can't seem to find a reliable way to calculate the inning offset for archived games.

**Comment by SlimJimPoisson** [comment]
I see the problem and don't have an easy solution, but I am curious if you have any idea how the MLB web-based player handles this?

**Comment by kmac** [comment]
I'm probably missing some sort of option in the request, but I spent quite a bit of time looking at the API and haven't found anything. There's definitely some sort of API there to do it, since I know the Roku MLB app can start archived games by inning. But I haven't been able to track it down. I usually just take the hit and download the entire archived game, then skip through to where it starts.
